version: 2.1

jobs:
  update_data:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r scripts/requirements.txt
      - run:
          name: Update data
          command: |
            . venv/bin/activate
            python scripts/update_data.py
      - run:
          name: Commit data back to Github
          command: |
            git config user.email "a.khalidomi@gmail.com"
            git config user.name "indifferent-omi"
            DATE_TODAY=$(date +"%Y-%m-%d")
            git pull origin main
            git commit -am "[skip ci] Updating Data ${DATE_TODAY}" --allow-empty
            git push origin main

workflows:
  daily_data_update:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - update_data